spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/api/test/** , /v3/api-docs/order , /v3/api-docs
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/api/auth/** , /v3/api-docs/identity , /v3/api-docs

  application:
    name: Taba-GATEWAY